In [1]:
import pandas as pd


df=pd.read_csv('../0-datasets//diabetes_two.csv')
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40.0,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58.0,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,NaN,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45.0,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,600.0,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

### Missing value check

In [3]:
df.isnull().sum()

Age                   1
Gender                1
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              1
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])
df.isnull().sum()

0    Male
Name: Gender, dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

In [13]:
df['Gender']=le.fit_transform(df['Gender'])
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40.0,1,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58.0,1,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,48.0,1,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45.0,1,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,600.0,1,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [14]:
df.columns

Index(['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss',
       'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring',
       'Itching', 'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class'],
      dtype='object')

In [15]:
df['Polyuria']=le.fit_transform(df['Polyuria'])
df['Polydipsia']=le.fit_transform(df['Polydipsia'])
df['sudden weight loss']=le.fit_transform(df['sudden weight loss'])
df['weakness']=le.fit_transform(df['weakness'])
df['Polyphagia']=le.fit_transform(df['Polyphagia'])
df['Genital thrush']=le.fit_transform(df['Genital thrush'])
df['visual blurring']=le.fit_transform(df['visual blurring'])
df['Itching']=le.fit_transform(df['Itching'])
df['Irritability']=le.fit_transform(df['Irritability'])
df['delayed healing']=le.fit_transform(df['delayed healing'])
df['partial paresis']=le.fit_transform(df['partial paresis'])
df['muscle stiffness']=le.fit_transform(df['muscle stiffness'])
df['Alopecia']=le.fit_transform(df['Alopecia'])
df['Obesity']=le.fit_transform(df['Obesity'])
df['class']=le.fit_transform(df['class'])

df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40.0,1,0,1,0,1,0,0,0,1,0,1,0,1,1,1,1
1,58.0,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,1
2,48.0,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,1
3,45.0,1,0,0,1,1,1,1,0,1,0,1,0,0,0,0,1
4,600.0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1