In [ ]:
import pandas as pd

weather = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "recordDate": pd.to_datetime([
        "2015-01-01",
        "2015-01-02",
        "2015-01-03",
        "2015-01-04"
    ]),
    "temperature": [10, 25, 20, 30]
})

display(weather)


prev_temp=weather['temperature'].shift(1)
prev_day=weather['recordDate'].shift(1)
display(prev_temp)
display(prev_day)

result=weather[
    (weather['temperature'] > prev_temp)  &  (weather['recordDate'] == prev_date + pd.Timedelta(days=1))
]

result[["id"]]

   id recordDate  temperature
0   1 2015-01-01           10
1   2 2015-01-02           25
2   3 2015-01-03           20
3   4 2015-01-04           30

0     NaN
1    10.0
2    25.0
3    20.0
Name: temperature, dtype: float64

0          NaT
1   2015-01-01
2   2015-01-02
3   2015-01-03
Name: recordDate, dtype: datetime64[ns]

   id
1   2
3   4